/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardServicosRouteImport } from './routes/dashboard.servicos'
import { Route as DashboardPortfolioRouteImport } from './routes/dashboard.portfolio'
import { Route as DashboardLandingRouteImport } from './routes/dashboard.landing'
import { Route as DashboardHorariosRouteImport } from './routes/dashboard.horarios'
import { Route as DashboardHistoricoRouteImport } from './routes/dashboard.historico'
import { Route as DashboardFinanceiroRouteImport } from './routes/dashboard.financeiro'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard.configuracoes'
import { Route as DashboardClientesRouteImport } from './routes/dashboard.clientes'
import { Route as DashboardAgendaRouteImport } from './routes/dashboard.agenda'
import { Route as DashboardClientesIdRouteImport } from './routes/dashboard.clientes.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicosRoute = DashboardServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPortfolioRoute = DashboardPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLandingRoute = DashboardLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHorariosRoute = DashboardHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoricoRoute = DashboardHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanceiroRoute = DashboardFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientesRoute = DashboardClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgendaRoute = DashboardAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientesIdRoute = DashboardClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/clientes': typeof DashboardClientesRouteWithChildren
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/historico': typeof DashboardHistoricoRoute
  '/dashboard/horarios': typeof DashboardHorariosRoute
  '/dashboard/landing': typeof DashboardLandingRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clientes/$id': typeof DashboardClientesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/clientes': typeof DashboardClientesRouteWithChildren
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/historico': typeof DashboardHistoricoRoute
  '/dashboard/horarios': typeof DashboardHorariosRoute
  '/dashboard/landing': typeof DashboardLandingRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/clientes/$id': typeof DashboardClientesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/clientes': typeof DashboardClientesRouteWithChildren
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/historico': typeof DashboardHistoricoRoute
  '/dashboard/horarios': typeof DashboardHorariosRoute
  '/dashboard/landing': typeof DashboardLandingRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clientes/$id': typeof DashboardClientesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/auth'
    | '/cliente'
    | '/dashboard'
    | '/reset-password'
    | '/dashboard/agenda'
    | '/dashboard/clientes'
    | '/dashboard/configuracoes'
    | '/dashboard/financeiro'
    | '/dashboard/historico'
    | '/dashboard/horarios'
    | '/dashboard/landing'
    | '/dashboard/portfolio'
    | '/dashboard/servicos'
    | '/dashboard/'
    | '/dashboard/clientes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/auth'
    | '/cliente'
    | '/reset-password'
    | '/dashboard/agenda'
    | '/dashboard/clientes'
    | '/dashboard/configuracoes'
    | '/dashboard/financeiro'
    | '/dashboard/historico'
    | '/dashboard/horarios'
    | '/dashboard/landing'
    | '/dashboard/portfolio'
    | '/dashboard/servicos'
    | '/dashboard'
    | '/dashboard/clientes/$id'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/auth'
    | '/cliente'
    | '/dashboard'
    | '/reset-password'
    | '/dashboard/agenda'
    | '/dashboard/clientes'
    | '/dashboard/configuracoes'
    | '/dashboard/financeiro'
    | '/dashboard/historico'
    | '/dashboard/horarios'
    | '/dashboard/landing'
    | '/dashboard/portfolio'
    | '/dashboard/servicos'
    | '/dashboard/'
    | '/dashboard/clientes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRoute
  AuthRoute: typeof AuthRoute
  ClienteRoute: typeof ClienteRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/servicos': {
      id: '/dashboard/servicos'
      path: '/servicos'
      fullPath: '/dashboard/servicos'
      preLoaderRoute: typeof DashboardServicosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portfolio': {
      id: '/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof DashboardPortfolioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/landing': {
      id: '/dashboard/landing'
      path: '/landing'
      fullPath: '/dashboard/landing'
      preLoaderRoute: typeof DashboardLandingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/horarios': {
      id: '/dashboard/horarios'
      path: '/horarios'
      fullPath: '/dashboard/horarios'
      preLoaderRoute: typeof DashboardHorariosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/historico': {
      id: '/dashboard/historico'
      path: '/historico'
      fullPath: '/dashboard/historico'
      preLoaderRoute: typeof DashboardHistoricoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/financeiro': {
      id: '/dashboard/financeiro'
      path: '/financeiro'
      fullPath: '/dashboard/financeiro'
      preLoaderRoute: typeof DashboardFinanceiroRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clientes': {
      id: '/dashboard/clientes'
      path: '/clientes'
      fullPath: '/dashboard/clientes'
      preLoaderRoute: typeof DashboardClientesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agenda': {
      id: '/dashboard/agenda'
      path: '/agenda'
      fullPath: '/dashboard/agenda'
      preLoaderRoute: typeof DashboardAgendaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clientes/$id': {
      id: '/dashboard/clientes/$id'
      path: '/$id'
      fullPath: '/dashboard/clientes/$id'
      preLoaderRoute: typeof DashboardClientesIdRouteImport
      parentRoute: typeof DashboardClientesRoute
    }
  }
}

interface DashboardClientesRouteChildren {
  DashboardClientesIdRoute: typeof DashboardClientesIdRoute
}

const DashboardClientesRouteChildren: DashboardClientesRouteChildren = {
  DashboardClientesIdRoute: DashboardClientesIdRoute,
}

const DashboardClientesRouteWithChildren =
  DashboardClientesRoute._addFileChildren(DashboardClientesRouteChildren)

interface DashboardRouteChildren {
  DashboardAgendaRoute: typeof DashboardAgendaRoute
  DashboardClientesRoute: typeof DashboardClientesRouteWithChildren
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardFinanceiroRoute: typeof DashboardFinanceiroRoute
  DashboardHistoricoRoute: typeof DashboardHistoricoRoute
  DashboardHorariosRoute: typeof DashboardHorariosRoute
  DashboardLandingRoute: typeof DashboardLandingRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  DashboardServicosRoute: typeof DashboardServicosRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgendaRoute: DashboardAgendaRoute,
  DashboardClientesRoute: DashboardClientesRouteWithChildren,
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardFinanceiroRoute: DashboardFinanceiroRoute,
  DashboardHistoricoRoute: DashboardHistoricoRoute,
  DashboardHorariosRoute: DashboardHorariosRoute,
  DashboardLandingRoute: DashboardLandingRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  DashboardServicosRoute: DashboardServicosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRoute,
  AuthRoute: AuthRoute,
  ClienteRoute: ClienteRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
